models/user.py
import hashlib

from sqlalchemy import Column, String, Text

import config
import secret
from models.base_model import SQLMixin, db


class User(SQLMixin, db.Model):
    __tablename__ = 'User'
    """
    User 是一个保存用户数据的 model
    现在只有两个属性 username 和 password
    """
    username = Column(String(50), nullable=False)
    password = Column(String(100), nullable=False)
    point = Column(String(100), nullable=False, default="10")
    image = Column(String(100), nullable=False, default='/images/默认头像.png')
    signature = Column(String(100), nullable=False, default=config.default_signature)
    email = Column(String(50), nullable=False, default=config.test_mail)

    @staticmethod
    def salted_password(password, salt='$!@><?>HUI&DWQa`'):
        salted = hashlib.sha256((password + salt).encode('ascii')).hexdigest()
        return salted

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        print('register', form)
        if User.validate_name(name) and User.one(username=name) is None:
            # 错误，只应该 commit 一次
            # u = User.new(form)
            # u.password = u.salted_password(pwd)
            # User.session.add(u)
            # User.session.commit()
            form['password'] = User.salted_password(form['password'])
            u = User.new(form)
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        query = dict(
            username=form['username'],
            password=User.salted_password(form['password']),
        )
        print('validate_login', form, query)
        return User.one(**query)

    @classmethod
    def validate_name(cls, name):
        return len(name) > 2

    @classmethod
    def validate_password(cls, password):
        return len(password) > 0

routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    # make_response,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, new_session

import json

import redis

cache = redis.StrictRedis()

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

import gevent
import threading
import time


@main.route("/register_view")
def register_view():
    return render_template("register_view.html")

@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    # gevent.spawn()
    time.sleep(0.5)
    print('time type', time.sleep, gevent.sleep)
    # u = current_user()
    return render_template("index.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session_id = new_session(u.id)

        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        return response


def created_topic(user_id):
    # O(n)
    # ts = Topic.all(user_id=user_id)
    # return ts
    #
    k = 'created_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        log('created v', v)
        ts = json.loads(v)
        log('created', 'key', k, ts, 'ts type<{}>'.format(type(ts)))
        return ts
    else:
        ts = Topic.all(user_id=user_id)
        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)
        log('created', ts)
        return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    # rs = Reply.all(user_id=user_id)
    # ts = []
    # for r in rs:
    #     t = Topic.one(id=r.topic_id)
    #     ts.append(t)
    # return ts
    #
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        log('replied', 'key', k, ts, 'ts type<{}>'.format(type(ts)))
        return ts
    else:
        rs = Reply.all(user_id=user_id)
        ts = []
        for r in rs:
            t = Topic.one(id=r.topic_id)
            ts.append(t)

        serialized_ts = []
        for i, t in enumerate(ts):
            ts.pop(i)
            log('replied t type', type(t), t)
            if t is not None:
                serialized_ts.append(t.json())
        v = json.dumps(serialized_ts)
        log('replied ts', ts)
        cache.set(k, v)
        return ts


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    # filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    filename = str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/reset.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
import uuid
import config
from models.message import send_mail
from models.user import User
from utils import log

main = Blueprint('reset', __name__)


@main.route('/send', methods=['POST'])
def send():
    form = request.form.to_dict()

    current_user = User.one(email=form['email'])
    if current_user is None:
        return redirect(url_for('index.index'))

    token = new_reset_token(current_user.id)
    content = '重置密码地址 {}://{}:{}{}?token={}'.format(
        config.protocol,
        config.host,
        config.port,
        url_for('.view'),
        token
    )
    log('重置密码地址', content)
    send_mail('重置密码', config.admin_mail, current_user.email, content)
    return redirect(url_for('index.index'))


@main.route('/view')
def view():
    log('token', request.args.get('token'), reset_tokens)
    token = request.args.get('token', '')
    if len(token) > 0:
        return render_template('reset/view.html', token=token)
    else:
        return redirect(url_for('index.index'))


@main.route('/index')
def index():
    return render_template('reset/index.html')


@main.route("/update",methods=['POST'])
def update():
    form = request.form.to_dict()
    password = form.get('password', '')
    token = form.get('token', '')
    id = reset_tokens.get(token, None)
    log('token and id', token, id, reset_tokens)
    if id is None:
        return redirect(url_for('index.index'))
    if User.validate_password(password):
        reset_tokens.pop(token)
        User.update(id, password=User.salted_password(password))
    return redirect(url_for('index.index'))


reset_tokens = dict()


def new_reset_token(user_id):
    token = str(uuid.uuid4())
    reset_tokens[token] = user_id
    return token

routes/setting.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
from werkzeug.datastructures import FileStorage

import config
from models.user import User
from routes import current_user


from utils import log

main = Blueprint('setting', __name__)


@main.route('/')
def index():
    print('running setting route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template(
            'setting.html',
            user=u,
            alert_error=None,
            alert_success=None,
        )


@main.route('/update_username_and_signature', methods=['POST'])
def update_username_and_signature():
    username = request.form.get('username', '')
    signature = request.form.get('signature', '')
    u = current_user()

    if signature == '':
        # 签名为空时使用默认签名
        signature = config.default_signature
    if not User.validate_name(username):
        username = u.username
    User.update(u.id, username=username, signature=signature)
    return redirect(url_for(".index"))


@main.route('/update_password', methods=['POST'])
def update_password():
    old_password = request.form.get('old_password', '')
    new_password = request.form.get('new_password', '')
    u = current_user()
    form = dict(
        username=u.username,
        password=old_password,
        )
    # 用验证登录的方法判断用户原密码是否正确
    if User.validate_login(form) is not None and User.validate_password(new_password):
        User.update(u.id, password=User.salted_password(new_password))
        return render_template(
            'setting.html',
            user=u,
            alert_error=None,
            alert_success='修改密码成功',
        )
    else:
        return render_template(
            'setting.html',
            user=u,
            alert_error="修改密码失败",
            alert_success=None,
        )


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    # filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    filename = str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('setting.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.message import Messages
from models.reply import Reply
from routes import *

from models.topic import Topic
from models.board import Board


main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
        top10_ms = Topic.all_order_by_view()[:10]
    else:
        ms = Topic.all(board_id=board_id)
        top10_ms = Topic.all_order_by_view(board_id=board_id)[:10]
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=current_user(), top10_ms=top10_ms)


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    liked = m.liked(u.id)
    return render_template("topic/detail.html", topic=m, user=u, liked=liked, id=m.id)


@main.route("/delete")
@csrf_required
def delete():
    u = current_user()
    created = 'created_topic_{}'.format(u.id)
    replied = 'replied_topic_{}'.format(u.id)
    cache.delete(created, replied)

    id = int(request.args.get('id'))
    print('删除 topic 用户是', u, id)
    t = Topic.one(id=id)
    for r in t.replies():
        Reply.delete(r.id)

    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/like")
def like():
    u = current_user()
    id = int(request.args.get('id'))
    t = Topic.one(id=id)
    print('like tid', t.id)
    t.like(u.id)
    send_like_me(u, t.user(), request.referrer, t.title)
    return redirect(url_for('.detail', id=t.id))


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


def send_like_me(sender, receiver, topic_link, topic_title):
    print('send_reply_me', sender, receiver, topic_title)
    content = topic_link

    title = '{} 点赞了你的 {}'.format(sender.username, topic_title)
    Messages.send(
        title=title,
        content=content,
        sender_id=sender.id,
        receiver_id=receiver.id,
        type='like_me',
    )

routes/user.py
from flask import (
    render_template,
    Blueprint,
)

from models.user import User
from models.topic import Topic
from models.reply import Reply
from utils import log

main = Blueprint('user', __name__)


@main.route("/<string:username>")
def index(username):
    user = User.one(username=username)
    created_topics = Topic.all_order_by_desc_time(user_id=user.id)
    replies = Reply.all_order_by_desc_time(user_id=user.id)
    # replies.sort(key=lambda r: r.created_time, reverse=True)
    # 通过 reply 查找参与过的 topic 会有重复，所以使用 set 避免加入重复的 topic
    participated_topics_set = set()
    participated_topics = []
    for r in replies:
        t = Topic.one(id=r.topic_id)
        if t not in participated_topics_set:
            participated_topics_set.add(t)
            participated_topics.append(t)
    # 对结果进行时间降序排序
    # topics.sort(key=lambda t: t.created_time, reverse=True)
    log('participated_topics', participated_topics)

    return render_template("user.html",
                           created_topics=created_topics,
                           participated_topics=participated_topics,
                           user=user)

templates/index.html
<!DOCTYPE html>
<html>
<head>
<title>划水</title>
<link href="../static/css/login.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" href="../images/划水.png" type="image/x-icon">
    <meta name="keywords" content="App Loction Form,Login Forms,Sign up Forms,Registration Forms,News latter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfonts-->
<link href='http://fonts.useso.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//webfonts-->
</head>
<body>
	<h1>划水吧</h1>
		<div class="app-location">
			<h2>进入划水俱乐部</h2>
			<div class="line"><span></span></div>
			<div class="location"><img src="../images/游泳圈.png" class="img-responsive" alt="" /></div>
			<form method="post" action="{{ url_for('.login') }}">
				<input type="text" name="username" class="text" value="密码123" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '用户名';}" >
				<input type="password" name="password" value="123" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '密码';}">
				<div class="submit"><input type="submit" onclick="myFunction()" value="登录" ></div>
				<div class="clear"></div>
				<div class="new">
					<h3><a href="{{ url_for("reset.index") }}">忘记密码？</a></h3>
					<h4><a href="{{ url_for("index.register_view") }}">一起划水</a></h4>
					<div class="clear"></div>
				</div>
			</form>
		</div>
	<!--start-copyright-->
   		<div class="copy-right">
				<p>Copyright &copy; 2015.Company name All rights reserved.</p>
		</div>
	<!--//end-copyright-->
</body>
</html>

templates/register_view.html
<!DOCTYPE html>
<html>
<head>
<title>划水</title>
<link href="../static/css/login.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" href="/images/划水.png" type="image/x-icon">
    <meta name="keywords" content="App Loction Form,Login Forms,Sign up Forms,Registration Forms,News latter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfonts-->
<link href='http://fonts.useso.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//webfonts-->
</head>
<body>
	<h1>划水吧</h1>
		<div class="app-location">
			<h2>加入划水俱乐部</h2>
			<div class="line"><span></span></div>
			<div class="location"><img src="../images/游泳圈.png" class="img-responsive" alt="" /></div>
			<form method="post" action="{{ url_for('.register') }}">
				<input type="text" name="email" class="text" value="邮箱" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '邮箱';}" >
				<input type="text" name="username" class="text" value="用户名" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '用户名';}" >
				<input type="password" name="password" value="密码" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '密码';}">
				<div class="submit"><input type="submit" onclick="myFunction()" value="注册" ></div>
				<div class="clear"></div>
				<div class="new">
					<h4><a href="{{ url_for('.index') }}">已有账号</a></h4>
					<div class="clear"></div>
				</div>
			</form>
		</div>
	<!--start-copyright-->
   		<div class="copy-right">
				<p>Copyright &copy; 2015.Company name All rights reserved.</p>
		</div>
	<!--//end-copyright-->
</body>
</html>

templates/user.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>bbs club</title>-->
    <!--<link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="/static/css/login.css">-->
<!--</head>-->
<!--<body>-->
{% extends "topic/base.html" %}
{% block title %}用户设置{% endblock%}
{% block main %}
<div id="main">
  <div id="sidebar">

  <div class="panel">

    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
  <div>
    <a class="user_avatar" href="/user/{{ user.username }}">
      <img src="{{ user.image }}" title="{{ user.username }}">
    </a>
    <span class="user_name"><a class="dark" href="{{ url_for('user.index', username=user.username) }}">{{ user.username }}</a></span>

    <div class="board clearfix">
    </div>
    <div class="space clearfix"></div>
{#    <span class="signature">#}
{#    {{ user.signature }}#}
{#    </span>#}
  </div>
</div>



    </div>

  </div>


  <div class="panel">
    <div class="inner">
      <a href="{{ url_for('topic.new', board_id=-1) }}" id="create_topic_btn">
        <span class="span-success">发布话题</span>
      </a>
    </div>
  </div>


</div>


<div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="https://cnodejs.org/">主页</a><span class="divider">/</span></li>
      </ul>
    </div>
    <div class="inner userinfo">
      <div class="user_big_avatar">
        <img src="{{ user.image }}" class="user_avatar" title={{ user.username }}>
      </div>
      <a class="dark">{{ user.username }}</a>

      <div class="user_profile">
{#        <ul class="unstyled">#}
{#          <span class="big">10</span> 积分#}




{#          <li>#}
{#            <i class="fa fa-lg fa-fw fa-github"></i>#}
{#            <a class="dark" href="https://github.com/Jimyfar" target="_blank">#}
{#              @Jimyfar#}
{#            </a>#}
{#          </li>#}


        </ul>
      </div>
      <p class="col_fade">{{ user.created_time | time_between_now }}</p>

    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近创建的话题</span>
    </div>
        {% for t in created_topics %}
            <div class="cell">
                <a class="user_avatar pull-left" href="/user/{{ user.username }}">
                    <img src="{{ user.image }}" title="{{ user.username }}">
                </a>
                <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t.replies() | count }}
                     </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                        {{ t.views }}
                    </span>
                </span>
                <span class="last_time pull-right">
                    {% if t.last_reply() != None %}
                        <a class="user_avatar" href="/user/{{ t.user().username }}">
                        <img class="user_small_avatar" src="{{ t.last_reply().user().image }}">
                        </a>

                        <span class="last_active_time">{{ t.last_reply().created_time | time_between_now }}</span>
                    {% else %}
                        <span class="last_active_time">{{ t.created_time | time_between_now }}</span>
                    {% endif %}
                </span>
                <a class='topic_title' href='/topic/{{ t.id }}' title='{{ t.title }}'>
      {{ t.title }}
    </a>
            </div>
        {% endfor %}
    </div>
</div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近参与的话题</span>
    </div>
        {% for t in participated_topics %}
            <div class="cell">
                <a class="user_avatar pull-left" href="/user/{{ t.user().username }}">
                    <img src="{{ t.user().image }}" title="{{ t.user().username }}">
                </a>
                <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t.replies() | count }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                        {{ t.views }}
                    </span>
                </span>
                <a class="user_avatar pull-right" href="/user/{{ t.last_reply().user().username }}">
                    <img class="user_small_avatar" src="{{ t.last_reply().user().image }}">
                    <span class="last_time pull-right">
                <span class="last_active_time">{{ t.last_reply().created_time | time_between_now }}</span>
                </span>
                </a>
                <a class='topic_title' href='/topic/{{ t.id }}' title='{{ t.title }}'>
                    {{ t.title }}
                </a>
            </div>
        {% endfor %}
{#    <div class="cell more">#}
{#      <a class="dark" href="https://cnodejs.org/user/Jimyfar/replies">查看更多»</a>#}
    </div>

  </div>
</div>


</div>

</body></html>
{% endblock%}