models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.like import Like
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)
    likes = Column(Integer, nullable=False, default=0)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def like(self, user_id):
        Like.new(self.id, user_id)
        self.likes += 1
        self.save()
        return self

    def liked(self, user_id):
        l = Like.one(topic_id=self.id, user_id=user_id)
        print('topic liked', user_id, self.id, l)
        if l is None:
            return False
        else:
            return True

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

    def last_reply(self):
        replies = Reply.all(topic_id=self.id)
        if len(replies) > 0:
            return replies[-1]
        else:
            return None

    @classmethod
    def all_order_by_view(cls, **kwargs):
        ms = cls.query.order_by(cls.views.desc()).filter_by(**kwargs).all()
        return ms

routes/message.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.like import Like
from models.topic import Topic
from routes import *

from models.message import Messages

main = Blueprint('mail', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    receiver_name = form['receiver_name']
    r = User.one(username=receiver_name)
    receiver_id = r.id
    # 发邮件
    Messages.send(
        title=form['title'],
        content=form['content'],
        sender_id=u.id,
        receiver_id=receiver_id,
        type=form['type'],
    )

    return redirect(url_for('.index'))


@main.route('/')
def index():
    u = current_user()

    send = Messages.all(sender_id=u.id, type='private_letter')
    received = Messages.all(receiver_id=u.id, type='private_letter')

    t = render_template(
        'mail/index.html',
        user=u,
        send=send,
        received=received,
    )
    return t


@main.route('/view/<int:id>')
def view(id):
    message = Messages.one(id=id)
    u = current_user()
    # if u.id == mail.receiver_id or u.id == mail.sender_id:
    if u.id in [message.receiver_id, message.sender_id]:
        return render_template('mail/detail.html', message=message)
    else:
        return redirect(url_for('.index'))


@main.route('/at_me')
def at_me():
    u = current_user()

    received = Messages.all(receiver_id=u.id, type='at_me')

    t = render_template(
        'mail/at_me.html',
        user=u,
        received=received,
    )
    return t


@main.route('/reply_me')
def reply_me():
    u = current_user()

    received = Messages.all(receiver_id=u.id, type='reply_me')

    t = render_template(
        'mail/reply_me.html',
        user=u,
        received=received,
    )
    return t


@main.route('/like_me')
def like_me():
    u = current_user()

    received = Messages.all(receiver_id=u.id, type='like_me')

    t = render_template(
        'mail/like_me.html',
        user=u,
        received=received,
    )
    return t

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    Request)

from models.message import Messages
from models.topic import Topic
from routes import *

from models.reply import Reply

main = Blueprint('reply', __name__)


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_at_me(sender, receivers, reply_link, reply_content):
    print('send_at_me', sender, receivers, reply_content)
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        title = '你被 {} AT 了'.format(sender.username)
        Messages.send(
            title=title,
            content=content,
            sender_id=sender.id,
            receiver_id=r.id,
            type='at_me',
        )


def send_reply_me(sender, receiver, reply_link, replied_topic_title):
    print('send_reply_me', sender, receiver, replied_topic_title)
    content = reply_link

    title = '{} 回复了你 {}'.format(sender.username, replied_topic_title)
    Messages.send(
        title=title,
        content=content,
        sender_id=sender.id,
        receiver_id=receiver.id,
        type='reply_me',
    )


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_at_me(u, users, request.referrer, content)

    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)

    tid = m.topic_id
    t = Topic.one(id=tid)

    send_reply_me(u, t.user(), request.referrer, t.title)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.message import Messages
from models.reply import Reply
from routes import *

from models.topic import Topic
from models.board import Board


main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
        top10_ms = Topic.all_order_by_view()[:10]
    else:
        ms = Topic.all(board_id=board_id)
        top10_ms = Topic.all_order_by_view(board_id=board_id)[:10]
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=current_user(), top10_ms=top10_ms)


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    liked = m.liked(u.id)
    return render_template("topic/detail.html", topic=m, user=u, liked=liked, id=m.id)


@main.route("/delete")
@csrf_required
def delete():
    u = current_user()
    created = 'created_topic_{}'.format(u.id)
    replied = 'replied_topic_{}'.format(u.id)
    cache.delete(created, replied)

    id = int(request.args.get('id'))
    print('删除 topic 用户是', u, id)
    t = Topic.one(id=id)
    for r in t.replies():
        Reply.delete(r.id)

    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/like")
def like():
    u = current_user()
    id = int(request.args.get('id'))
    t = Topic.one(id=id)
    print('like tid', t.id)
    t.like(u.id)
    send_like_me(u, t.user(), request.referrer, t.title)
    return redirect(url_for('.detail', id=t.id))


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


def send_like_me(sender, receiver, topic_link, topic_title):
    print('send_reply_me', sender, receiver, topic_title)
    content = topic_link

    title = '{} 点赞了你的 {}'.format(sender.username, topic_title)
    Messages.send(
        title=title,
        content=content,
        sender_id=sender.id,
        receiver_id=receiver.id,
        type='like_me',
    )

routes/user.py
from flask import (
    render_template,
    Blueprint,
)

from models.user import User
from models.topic import Topic
from models.reply import Reply
from utils import log

main = Blueprint('user', __name__)


@main.route("/<string:username>")
def index(username):
    user = User.one(username=username)
    created_topics = Topic.all_order_by_desc_time(user_id=user.id)
    replies = Reply.all_order_by_desc_time(user_id=user.id)
    # replies.sort(key=lambda r: r.created_time, reverse=True)
    # 通过 reply 查找参与过的 topic 会有重复，所以使用 set 避免加入重复的 topic
    participated_topics_set = set()
    participated_topics = []
    for r in replies:
        t = Topic.one(id=r.topic_id)
        if t not in participated_topics_set:
            participated_topics_set.add(t)
            participated_topics.append(t)
    # 对结果进行时间降序排序
    # topics.sort(key=lambda t: t.created_time, reverse=True)
    log('participated_topics', participated_topics)

    return render_template("user.html",
                           created_topics=created_topics,
                           participated_topics=participated_topics,
                           user=user)

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head>
    <title>{% block title %}{% endblock %}</title>
 <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <!-- meta -->
  <meta charset="utf-8">
  <meta name="description" content="CNode：Node.js专业中文社区">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="nodejs, node, express, connect, socket.io">
  <!-- see http://smerity.com/articles/2013/where_did_all_the_http_referrers_go.html -->
  <meta name="referrer" content="always">


<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">


  <link title="RSS" type="application/rss+xml" rel="alternate" href="https://cnodejs.org/rss">


  <link rel="icon" href="../../images/划水.png" type="image/x-icon">


  <!-- style -->
  <link rel="stylesheet" href="/static/css/index.css" media="all">


  <!-- scripts -->
  <script async="" src="/static/js/setting.js"></script><script src="/static/js/index.js"></script>



  <title>CNode：Node.js专业中文社区</title>

  <meta content="_csrf" name="csrf-param">
  <meta content="wVId0zEM-x2-jSgNUAcu7cd-HioUu5gjquKg" name="csrf-token">

</head>
<body>

<!-- navbar -->
<div class="navbar-parent">
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <ul class='nav pull-left'>
          <li><a style="padding: 5px;" class="user_avatar" href="{{ url_for('user.index', username=user.username) }}">
      <img style="padding: -10px -10px" src="{{ user.image }}" title="{{ user.username }}">
    </a></li>
          <li><a href='/'>首页</a></li>
          <li><a href='{{ url_for('topic.index') }}'>话题</a></li>
          <li><a href="{{ url_for('setting.index') }}" target="">设置</a></li>
        <li><a href="{{ url_for('mail.index', username=user.username) }}" target="">私信</a></li>
        <li><a href='{{ url_for('user.index', username=user.username) }}'>个人信息</a></li>


      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
</div>
{% block main %}
{% endblock %}

<div id="backtotop" style="top: 323px; right: 0px; display: none;">回到顶部</div>
<div id="footer">
  <div id="footer_main">
    <div class="links">
      <a class="dark" href="https://github.com/jimyfar/">源码地址</a>
    </div>

    <div class="col_fade">

</div>


  </div>
</div>
<div id="sidebar-mask"></div>
<script>
  // google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script', "https://www.google-analytics.com/setting.js",'ga');

  ga('create', 'UA-41753901-5', 'auto');
  ga('send', 'pageview');
</script>
</body>

templates/topic/detail.html
{% extends "topic/base.html" %}

{% block title %}{{ topic.title }}{% endblock%}

{% block main %}
    </div>
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
                    <span>
                {% set u = topic.user() %}
                        作者
                <a href="{{ url_for('user.index', username=u.username) }}">
                    {{ u.username }}
                </a>

        	</span>
                    <span>
                发布于 2 天前
            </span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content}}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel' id="content">
        <div class='header topic_header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
            <span class='col_fade like-count'>{{ topic.likes }}</span><span>已赞</span>
            {% if liked == False %}
              <span class='col_fade pull-right'>
                <a href="{{ url_for('.like', id=topic.id) }}">
                  <button aria-label="赞同" type="button" class="like">赞同</button>
                    <a>
            </span>
                {% else %}
                <span class='col_fade pull-right'>
                <a>
                  <button aria-label="赞同" type="button" class="like">已赞</button>
                    <a>
            </span>
            {% endif %}


        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span>{{ r.created_time }}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content }}</div>

                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>

    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    document.querySelector(".like").addEventListener("click", function (event) {
        b = event.target

        if ( b.innerHTML != "已赞"){
            likeCount = document.querySelector(".like-count")
        console.log("likeCount", likeCount)
        i = parseInt(likeCount.innerHTML) + 1
        likeCount.innerHTML = i
        }
        b.innerHTML = "已赞"

    })


    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>

{% endblock %}

templates/topic/index.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>bbs club</title>-->
    <!--<link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="/static/css/login.css">-->
<!--</head>-->
<!--<body>-->
{% extends "topic/base.html" %}
{% block title %}开始划水{% endblock%}
{% block main %}

<div id="main">
  <div id="sidebar">

  <div class="panel">
    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
  <div>
    <a class="user_avatar" href="{{ url_for('user.index', username=user.username) }}">
      <img src="{{ user.image }}" title="{{ user.username }}">
    </a>
    <span class="user_name"><a class="dark" href="{{ url_for('user.index', username=user.username) }}">{{ user.username }}</a></span>

    <div class="board clearfix">
      <div class="floor">
        <span class="big">积分: {{ user.point }} </span>
      </div>
    </div>
    <div class="space clearfix"></div>
    <span class="signature">
   {{ user.signature }}
    </span>
  </div>
</div>





    </div>

  </div>


  <div class="panel">
    <div class="inner">
      <a href="{{ url_for('topic.new', board_id=-1) }}" id="create_topic_btn">
        <span class="span-success">发布话题</span>
      </a>
    </div>

  </div>
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    浏览排行
                </a>
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in top10_ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>


                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
</div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>


                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>
    <script>
  $(document).ready(function () {
    $('.follow_btn').click(function () {
      var $me = $(this);
      var action = $me.attr('action');
      var params = {
        follow_id: '5d076ae895fcc914aa269eb3',
        _csrf: 'wVId0zEM-x2-jSgNUAcu7cd-HioUu5gjquKg'
      };
      $.post('/user/' + action, params, function (data) {
        if (data.status === 'success') {
          var $btns = $('.follow_btn');
          if (action === 'follow') {
            $btns.html('取消关注');
            $btns.attr('action', 'un_follow');
          } else {
            $btns.html('加入关注');
            $btns.attr('action', 'follow');
          }
          $btns.toggleClass('btn-success');
        }
      }, 'json');
    });
  });
</script>

{% endblock %}


<!--</body>-->
<!--</html>-->

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
<!--<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">-->
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>