routes/reset.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
import uuid
import config
from models.message import send_mail
from models.user import User
from utils import log

main = Blueprint('reset', __name__)


@main.route('/send', methods=['POST'])
def send():
    form = request.form.to_dict()

    current_user = User.one(email=form['email'])
    if current_user is None:
        return redirect(url_for('index.index'))

    token = new_reset_token(current_user.id)
    content = '重置密码地址 {}://{}:{}{}?token={}'.format(
        config.protocol,
        config.host,
        config.port,
        url_for('.view'),
        token
    )
    log('重置密码地址', content)
    send_mail('重置密码', config.admin_mail, current_user.email, content)
    return redirect(url_for('index.index'))


@main.route('/view')
def view():
    log('token', request.args.get('token'), reset_tokens)
    token = request.args.get('token', '')
    if len(token) > 0:
        return render_template('reset/view.html', token=token)
    else:
        return redirect(url_for('index.index'))


@main.route('/index')
def index():
    return render_template('reset/index.html')


@main.route("/update",methods=['POST'])
def update():
    form = request.form.to_dict()
    password = form.get('password', '')
    token = form.get('token', '')
    id = reset_tokens.get(token, None)
    log('token and id', token, id, reset_tokens)
    if id is None:
        return redirect(url_for('index.index'))
    if User.validate_password(password):
        reset_tokens.pop(token)
        User.update(id, password=User.salted_password(password))
    return redirect(url_for('index.index'))


reset_tokens = dict()


def new_reset_token(user_id):
    token = str(uuid.uuid4())
    reset_tokens[token] = user_id
    return token

templates/reset/index.html
<!DOCTYPE html>
<html>
<head>
<title>划水</title>
<link href="../../static/css/login.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" href="../../images/划水.png" type="image/x-icon">
    <meta name="keywords" content="App Loction Form,Login Forms,Sign up Forms,Registration Forms,News latter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfonts-->
<link href='http://fonts.useso.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//webfonts-->
</head>
<body>
	<h1>重置密码</h1>
		<div class="app-location">
			<div class="location"><img src="../../images/游泳圈.png" class="img-responsive" alt="" /></div>
			<form method="post" action="{{ url_for("reset.send") }}">
				<input type="text" name="email" class="text" value="E-mail address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'E-mail address';}" >
				<div class="submit"><input type="submit" onclick="myFunction()" value="发送到邮箱" ></div>
				<div class="clear"></div>
				<div class="new">
				</div>
			</form>
		</div>
	<!--start-copyright-->
   		<div class="copy-right">
				<p>Copyright &copy; 2015.Company name All rights reserved.</p>
		</div>
	<!--//end-copyright-->
</body>
</html>

templates/reset/send_success.html
<!DOCTYPE html>
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>bbs club</title>-->
    <!--<link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="/static/css/login.css">-->
<!--</head>-->
<!--<body>-->
{% extends "topic/base.html" %}
{% block title %}发送邮箱成功{% endblock%}
{% block main %}
    <form class="form-horizontal" method="post" action="{{ url_for('reset.send') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username" value="{{ username }}">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="重新发送邮箱">
        </div>
    </form>
{% endblock%}

templates/reset/view.html
<!DOCTYPE html>
<html>
<head>
<title>划水</title>
<link href="../static/css/login.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" href="../images/划水.png" type="image/x-icon">
    <meta name="keywords" content="App Loction Form,Login Forms,Sign up Forms,Registration Forms,News latter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfonts-->
<link href='http://fonts.useso.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//webfonts-->
</head>
<body>
	<h1>划水吧</h1>
		<div class="app-location">
			<h2></h2>
			<div class="line"><span></span></div>
			<div class="location"><img src="/images/游泳圈.png" class="img-responsive" alt="" /></div>
			<form method="post" action="{{ url_for('.update') }}">
				<input type="password" name="password" value="密码" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '密码';}">
				<input type="hidden" name="token" value="{{ token }}" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '密码';}">
				<div class="submit"><input type="submit" onclick="myFunction()" value="重置密码" ></div>
				<div class="clear"></div>
				<div class="new">
					<h4><a href="{{ url_for('.index') }}">已有账号</a></h4>
					<div class="clear"></div>
				</div>
			</form>
		</div>
	<!--start-copyright-->
   		<div class="copy-right">
				<p>Copyright &copy; 2015.Company name All rights reserved.</p>
		</div>
	<!--//end-copyright-->
</body>
</html>